### ISSUE TITLE
URL Shorteners

### ISSUE THREAD

**Issue by ArmynC** [piperun/iploggerfilter#30]
For some time, I often meet the _bit.ly_ element in many sites. The problem is that now I have to disable the filter for many of them and evenmore, when I press a link that goes through a shortener like this, there is no option to 'temporary allow it' and the tab just vanish.

So, is there any way to disable just the "logging" features from these shorteners and still use them or this is impossible and they must be whitelisted? After all, it is important to have them in the filter?

**Comment by Thunder33345** [comment]
Agreed with this,
@piperun is it really necessary to block redirectors?
since assuming we cover all of the ip loggers, redirectors must pass through them as most normal ones dont log/show ip

**Comment by piperun** [comment]
This is excepted behavior since I added `^$all` to it.
Unfortunately, web browsers don't have the capability of blocking server-side code that tracks IP addresses, the closest we can do is to block that website entirely.
The exception being javascript, but most IP loggers either rely on server-side code or IP logs from their software.

@Thunder33345 
Some redirectors have IP tracking as part of their feature, thus they qualify on being blocked.

bitly has been tricky overall since one moment they brag about having IP tracking and the other they don't.

**Comment by Thunder33345** [comment]
while yes most of them "track" it for analytics/whatever reasons, we may never know
but most of them dont just flaunt or even display the data to anyone except internal staff
and i think that in itself is a good qualifier to consider if they are malicious:
`Can a normal person who created view the ip logs`
Since normally only malicious trackers does that, and i think aggregate data is fine(like for analytics reason where ip is never directly exposed)

**Comment by piperun** [comment]
That's specifically the rule iplogger follows, which is only a few legit url shorteners are on the list..

I'll remove bit.ly since it does not show IP with their "Free" version.
Since that was what this topic was about, I'll be closing the issue.
