### ISSUE TITLE
Use domain anchors?

### ISSUE THREAD

**Issue by toshiya44** [piperun/iploggerfilter#4]
Filters like `example.com` are interpreted as "block network requests which URL contains `example.com` at any position". 
Using `||example.com` will cause it to be interpreted as "block network requests to the site `example.com`" (including subdomains, which means you can just write `||example.com` instead of `*.example.com` ).

Here's what I'm asking to do https://gist.github.com/toshiya44/b10983c1edc5da14147a59a08a4742c5/raw

**Comment by piperun** [comment]
Interesting, I have to say I missed the syntax mainly because I wanted to add them later on, but alas I forgot.

But since these days the only reasonable adblock seems to be ublock, I'll change it into what you are purposing, although it'll be a bit more slower change to make sure I don't repeat the `*.appspot.com` mistake.
